const ysr = {
    CONTACT: "17757702217",
    DUTY: "网格员",
    NAME: "姚思如",
    ORGCODE: "1.1.14.3.87.2.6.",
    ORGNAME: "鹿城-蒲鞋市-0031（3556网格）"
}
const hxk = {
    CONTACT: "17757702102",
    DUTY: "网格员",
    NAME: "黄新康",
    ORGCODE: "1.1.14.3.87.5.2.",
    ORGNAME: "鹿城-蒲鞋市-0016（3502网格）"
}
const yj = {
    CONTACT: "17757702131",
    DUTY: "网格员",
    NAME: "余洁",
    ORGCODE: "1.1.14.3.87.2.11.",
    ORGNAME: "鹿城-蒲鞋市-0036（3561网格）"
}
export default {
    8587: yj,
    8586: yj,
    8538: yj,
    7369: ysr,
    7368: ysr,
    7367: ysr,
    1670: hxk,
    5251: hxk,
    4867: hxk,
}