const ysr = {
    CONTACT: "17757702217",
    DUTY: "网格员",
    NAME: "姚思如",
    ORGCODE: "1.1.14.3.87.2.6.",
    ORGNAME: "鹿城-蒲鞋市-0031（3556网格）"
}
const xzy = {
    CONTACT: "17706675893",
    DUTY: "网格员",
    NAME: "许朝阳",
    ORGCODE: "1.1.14.3.87.6.4.",
    ORGNAME: "鹿城-蒲鞋市-0072（3754网格）"
}
const yj = {
    CONTACT: "17757702131",
    DUTY: "网格员",
    NAME: "余洁",
    ORGCODE: "1.1.14.3.87.2.11.",
    ORGNAME: "鹿城-蒲鞋市-0036（3561网格）"
}
const lyy = {
    CONTACT: "17757702267",
    DUTY: "社区工作人员",
    NAME: "李盈颖",
    ORGCODE: "1.1.14.3.87.7.2.",
    ORGNAME: "鹿城-蒲鞋市-0077（3608网格）"
}
export default {
    8587: yj,
    8586: yj,
    8538: yj,
    7369: ysr,
    7368: ysr,
    7367: ysr,
    1670: xzy,
    5251: xzy,
    4867: xzy,
    6712: lyy
}